base_config: "base.yml"

logical_axis_rules: [
                      ['activation_heads', ['tensor', 'autoregressive']],
                      ['activation_kv_heads', ['tensor']],
                      ['activation_embed', ['tensor', 'autoregressive']],
                      ['activation_mlp', ['tensor', 'autoregressive']],
                      ['activation_vocab', ['tensor', 'autoregressive']],
                      ['mlp', ['tensor', 'autoregressive']],
                      ['vocab', ['tensor', 'autoregressive']],
                      ['norm', ['tensor', 'autoregressive']],
                      ['heads', ['tensor', 'autoregressive']],
                      ['kv_heads', ['tensor']],
                      ['cache_batch', ['autoregressive']],
                      ['cache_heads', ['tensor']],
                      ['cache_scale_batch', ['autoregressive']],
                    ]
